//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComsumingRESTServiceCRUD_client.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/DemoRESTServiceCRUD")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((this.BookIdField.Equals(value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBookServices")]
    public interface IBookServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServices/GetBookList", ReplyAction="http://tempuri.org/IBookServices/GetBookListResponse")]
        ComsumingRESTServiceCRUD_client.ServiceReference1.Book[] GetBookList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServices/GetBookList", ReplyAction="http://tempuri.org/IBookServices/GetBookListResponse")]
        System.Threading.Tasks.Task<ComsumingRESTServiceCRUD_client.ServiceReference1.Book[]> GetBookListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServices/GetBookById", ReplyAction="http://tempuri.org/IBookServices/GetBookByIdResponse")]
        ComsumingRESTServiceCRUD_client.ServiceReference1.Book GetBookById(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServices/GetBookById", ReplyAction="http://tempuri.org/IBookServices/GetBookByIdResponse")]
        System.Threading.Tasks.Task<ComsumingRESTServiceCRUD_client.ServiceReference1.Book> GetBookByIdAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServices/AddBook", ReplyAction="http://tempuri.org/IBookServices/AddBookResponse")]
        string AddBook(ComsumingRESTServiceCRUD_client.ServiceReference1.Book book, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServices/AddBook", ReplyAction="http://tempuri.org/IBookServices/AddBookResponse")]
        System.Threading.Tasks.Task<string> AddBookAsync(ComsumingRESTServiceCRUD_client.ServiceReference1.Book book, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServices/UpdateBook", ReplyAction="http://tempuri.org/IBookServices/UpdateBookResponse")]
        string UpdateBook(ComsumingRESTServiceCRUD_client.ServiceReference1.Book book, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServices/UpdateBook", ReplyAction="http://tempuri.org/IBookServices/UpdateBookResponse")]
        System.Threading.Tasks.Task<string> UpdateBookAsync(ComsumingRESTServiceCRUD_client.ServiceReference1.Book book, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServices/DeleteBook", ReplyAction="http://tempuri.org/IBookServices/DeleteBookResponse")]
        string DeleteBook(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookServices/DeleteBook", ReplyAction="http://tempuri.org/IBookServices/DeleteBookResponse")]
        System.Threading.Tasks.Task<string> DeleteBookAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookServicesChannel : ComsumingRESTServiceCRUD_client.ServiceReference1.IBookServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServicesClient : System.ServiceModel.ClientBase<ComsumingRESTServiceCRUD_client.ServiceReference1.IBookServices>, ComsumingRESTServiceCRUD_client.ServiceReference1.IBookServices {
        
        public BookServicesClient() {
        }
        
        public BookServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ComsumingRESTServiceCRUD_client.ServiceReference1.Book[] GetBookList() {
            return base.Channel.GetBookList();
        }
        
        public System.Threading.Tasks.Task<ComsumingRESTServiceCRUD_client.ServiceReference1.Book[]> GetBookListAsync() {
            return base.Channel.GetBookListAsync();
        }
        
        public ComsumingRESTServiceCRUD_client.ServiceReference1.Book GetBookById(string id) {
            return base.Channel.GetBookById(id);
        }
        
        public System.Threading.Tasks.Task<ComsumingRESTServiceCRUD_client.ServiceReference1.Book> GetBookByIdAsync(string id) {
            return base.Channel.GetBookByIdAsync(id);
        }
        
        public string AddBook(ComsumingRESTServiceCRUD_client.ServiceReference1.Book book, string id) {
            return base.Channel.AddBook(book, id);
        }
        
        public System.Threading.Tasks.Task<string> AddBookAsync(ComsumingRESTServiceCRUD_client.ServiceReference1.Book book, string id) {
            return base.Channel.AddBookAsync(book, id);
        }
        
        public string UpdateBook(ComsumingRESTServiceCRUD_client.ServiceReference1.Book book, string id) {
            return base.Channel.UpdateBook(book, id);
        }
        
        public System.Threading.Tasks.Task<string> UpdateBookAsync(ComsumingRESTServiceCRUD_client.ServiceReference1.Book book, string id) {
            return base.Channel.UpdateBookAsync(book, id);
        }
        
        public string DeleteBook(string id) {
            return base.Channel.DeleteBook(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteBookAsync(string id) {
            return base.Channel.DeleteBookAsync(id);
        }

        internal string UpdateBook(Book book)
        {
            throw new NotImplementedException();
        }

        internal string AddBook(Book books)
        {
            throw new NotImplementedException();
        }
    }
}
